Repository TriliumNext/Trilium, pull requests merged in 2025-07, with the labels that each got.

#6206 Tree context menu: reorder the note types of "Insert (child) note..."
  apps/client/src/services/note_types.ts
  apps/client/src/widgets/note_type.ts
Labels: size:M, lgtm

#6104 Feature/note map filter
  apps/client/src/widgets/note_map.ts
  apps/server/src/routes/api/note_map.ts
  apps/server/src/services/builtin_attributes.ts
  docs/User Guide/User Guide/Note Types/Note Map.md
Labels: size:S, lgtm

#6097 Introduce the table view
  apps/client/package.json
  apps/client/src/components/component.ts
  apps/client/src/components/note_context.ts
  apps/client/src/menus/context_menu.ts
  apps/client/src/services/attributes.ts
  apps/client/src/services/content_renderer.ts
  apps/client/src/services/link.ts
  apps/client/src/services/note_list_renderer.ts
  apps/client/src/services/note_tooltip.ts
  apps/client/src/services/promoted_attribute_definition_parser.ts
  apps/client/src/translations/en/translation.json
  apps/client/src/widgets/floating_buttons/help_button.ts
  apps/client/src/widgets/note_list.ts
  apps/client/src/widgets/ribbon_widgets/book_properties.ts
  apps/client/src/widgets/ribbon_widgets/promoted_attributes.ts
  apps/client/src/widgets/search_result.ts
  apps/client/src/widgets/type_widgets/book.ts
  apps/client/src/widgets/view_widgets/calendar_view.ts
  apps/client/src/widgets/view_widgets/list_or_grid_view.ts
  apps/client/src/widgets/view_widgets/table_view/columns.ts
  apps/client/src/widgets/view_widgets/table_view/dragging.ts
  apps/client/src/widgets/view_widgets/table_view/footer.ts
  apps/client/src/widgets/view_widgets/table_view/formatters.ts
  apps/client/src/widgets/view_widgets/table_view/header-menu.ts
  apps/client/src/widgets/view_widgets/table_view/index.ts
  apps/client/src/widgets/view_widgets/table_view/relation_editor.ts
  apps/client/src/widgets/view_widgets/table_view/rows.ts
  apps/client/src/widgets/view_widgets/view_mode.ts
  apps/client/src/widgets/view_widgets/view_mode_storage.ts
  apps/server/src/assets/doc_notes/en/User Guide/!!!meta.json
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/Notes/Note List/Table.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/Notes/Note List/Table_image.png
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Note Types/Note Map.html
  apps/server/src/routes/api/attributes.ts
  apps/server/src/services/hidden_subtree_templates.ts
  docs/Developer Guide/!!!meta.json
  docs/Release Notes/!!!meta.json
  docs/Release Notes/Release Notes/v0.96.0.md
  docs/User Guide/!!!meta.json
  docs/User Guide/User Guide/Basic Concepts and Features/Notes/Note List/Table.md
  docs/User Guide/User Guide/Basic Concepts and Features/Notes/Note List/Table_image.png
  docs/User Guide/User Guide/Note Types/Note Map.md
  pnpm-lock.yaml
Labels: size:XXL

#6243 fix(api): implement better rate limiting controls for pre-auth endpoints
  apps/server/src/routes/routes.ts
Labels: size:XS

#6263 Update docker-compose.yml with new container image
  docker-compose.yml
Labels: size:XS

#6299 Tree Context Menu: relocate the "Duplicate subtree" menu item
  apps/client/src/menus/tree_context_menu.ts
  apps/client/src/translations/cn/translation.json
  apps/client/src/translations/de/translation.json
  apps/client/src/translations/en/translation.json
  apps/client/src/translations/es/translation.json
  apps/client/src/translations/fr/translation.json
  apps/client/src/translations/ro/translation.json
  apps/client/src/translations/tw/translation.json
  apps/server/src/assets/doc_notes/en/User Guide/!!!meta.json
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Advanced Usage/Sharing.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/Notes/Note List/Calendar View.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/Notes/Note List/Geo Map View.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/Notes/Note List/Grid View.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/Notes/Note List/List View.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tooltip.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tree.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tree/1_Note tree contextual menu_.png
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tree/Keyboard shortcuts.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tree/Note tree contextual menu.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tree/Note tree contextual menu_.png
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Basic Concepts and Features/UI Elements/Quick edit.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Feature Highlights.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Note Types.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Note Types/Collections.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Note Types/Text/Links.html
  docs/User Guide/!!!meta.json
  docs/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tree/1_Note tree contextual menu_.png
  docs/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tree/Note tree contextual menu.md
  docs/User Guide/User Guide/Basic Concepts and Features/UI Elements/Note Tree/Note tree contextual menu_.png
Labels: UI, size:S

#6344 Update README.md
  README.md
Labels: size:S, lgtm

#6352 fix(api): also rate limit etapi docs endpoint
  apps/server/src/etapi/spec.ts
Labels: size:XS

#6402 Kanban board
  .github/instructions/nx.instructions.md
  .vscode/mcp.json
  .vscode/settings.json
  apps/client/src/components/note_context.ts
  apps/client/src/services/bulk_action.ts
  apps/client/src/services/note_list_renderer.ts
  apps/client/src/translations/en/translation.json
  apps/client/src/widgets/floating_buttons/help_button.ts
  apps/client/src/widgets/ribbon_widgets/book_properties.ts
  apps/client/src/widgets/ribbon_widgets/book_properties_config.ts
  apps/client/src/widgets/tab_row.ts
  apps/client/src/widgets/type_widgets/book.ts
  apps/client/src/widgets/view_widgets/board_view/api.ts
  apps/client/src/widgets/view_widgets/board_view/config.ts
  apps/client/src/widgets/view_widgets/board_view/context_menu.ts
  apps/client/src/widgets/view_widgets/board_view/data.ts
  apps/client/src/widgets/view_widgets/board_view/differential_renderer.ts
  apps/client/src/widgets/view_widgets/board_view/drag_handler.ts
  apps/client/src/widgets/view_widgets/board_view/index.ts
  apps/client/src/widgets/view_widgets/table_view/bulk_actions.ts
  apps/client/src/widgets/widget_utils.ts
  apps/server/src/assets/translations/en/server.json
  apps/server/src/services/hidden_subtree_templates.ts
Labels: size:XXL

#6513 Translations update from Hosted Weblate
  apps/client/src/translations/cn/translation.json
  apps/client/src/translations/de/translation.json
  apps/client/src/translations/es/translation.json
  apps/client/src/translations/fr/translation.json
  apps/client/src/translations/pt_br/translation.json
  apps/client/src/translations/ro/translation.json
  apps/client/src/translations/tw/translation.json
Labels: size:S, lgtm

#6516 Translations update from Hosted Weblate
  apps/client/src/translations/es/translation.json
  apps/client/src/translations/sr/translation.json
  apps/server/src/assets/translations/es/server.json
Labels: size:XL, lgtm
