Repository TriliumNext/Trilium, pull requests merged in 2025-10, with the labels that each got.

#7175 Translations update from Hosted Weblate
  apps/client/src/translations/nb-NO/translation.json
  apps/client/src/translations/ro/translation.json
  apps/server/src/assets/translations/nb-NO/server.json
  apps/server/src/assets/translations/ro/server.json
Labels: size:S, lgtm

#7174 Equation improvements
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Note Types/Text/Math Equations.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Scripting/Logging.html
  docs/User Guide/User Guide/Note Types/Text/Math Equations.md
  packages/ckeditor5-math/src/mathcommand.ts
  packages/ckeditor5-math/src/mathediting.ts
Labels: size:M

#7205 Translations update from Hosted Weblate
  docs/README-ja.md
Labels: size:L

#7157 feat: Add shareHtml relation for custom HTML snippets in shared pages
  apps/server/src/services/builtin_attributes.ts
  docs/User Guide/User Guide/Advanced Usage/Attributes/Relations.md
  docs/User Guide/User Guide/Advanced Usage/Sharing.md
  packages/share-theme/src/templates/page.ejs
Labels: size:M, lgtm
