Repository TriliumNext/Trilium, pull requests merged in 2025-08, with the labels that each got.

#6534 Translations update from Hosted Weblate
  apps/client/src/translations/sr/translation.json
Labels: size:L, lgtm

#6540 Translations update from Hosted Weblate
  apps/client/src/translations/cn/translation.json
  apps/client/src/translations/es/translation.json
  apps/client/src/translations/ja/translation.json
  apps/server/src/assets/translations/cn/server.json
  apps/server/src/assets/translations/de/server.json
  apps/server/src/assets/translations/es/server.json
Labels: size:XXL

#6552 Translations update from Hosted Weblate
  apps/client/src/translations/ca/translation.json
  apps/client/src/translations/cn/translation.json
  apps/client/src/translations/el/translation.json
  apps/client/src/translations/it/translation.json
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/pt_br/translation.json
  apps/client/src/translations/ru/translation.json
  apps/client/src/translations/sr/translation.json
  apps/server/src/assets/translations/ca/server.json
  apps/server/src/assets/translations/cn/server.json
  apps/server/src/assets/translations/fr/server.json
  apps/server/src/assets/translations/it/server.json
  apps/server/src/assets/translations/pt_br/server.json
  apps/server/src/assets/translations/tw/server.json
Labels: size:XXL, lgtm

#6578 Translations update from Hosted Weblate
  apps/server/src/assets/translations/it/server.json
Labels: size:M, lgtm

#6579 Translations update from Hosted Weblate
  apps/server/src/assets/translations/el/server.json
  apps/server/src/assets/translations/ja/server.json
  apps/server/src/assets/translations/ru/server.json
  apps/server/src/assets/translations/sr/server.json
Labels: size:XS

#6585 Translations update from Hosted Weblate
  apps/client/src/translations/pt_br/translation.json
  apps/client/src/translations/tr/translation.json
  apps/server/src/assets/translations/tr/server.json
Labels: size:L

#6568 Added Simple Update/Autoupdate Script
  docs/User Guide/User Guide/Installation & Setup/Server Installation/1. Installing the server/Packaged version for Linux.md
Labels: size:L, lgtm

#6554 fix: remove unnecessary idea directory
  .gitignore
  .idea/.gitignore
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dataSources.xml
  .idea/encodings.xml
  .idea/git_toolbox_prj.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLibraryMappings.xml
  .idea/jsLinters/jslint.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/sqldialects.xml
  .idea/vcs.xml
  apps/web-clipper/.idea/.gitignore
  apps/web-clipper/.idea/inspectionProfiles/Project_Default.xml
  apps/web-clipper/.idea/misc.xml
  apps/web-clipper/.idea/modules.xml
  apps/web-clipper/.idea/vcs.xml
Labels: size:L, lgtm

#6603 Translations update from Hosted Weblate
  apps/client/src/translations/vi/translation.json
  apps/server/src/assets/translations/vi/server.json
Labels: size:M, lgtm

#6596 Adds a get/set to bNote to allow getting an Attribute by it's Id, or …
  apps/server/src/becca/entities/bnote.ts
Labels: size:M, lgtm

#6620 only run nightly.yml on TriliumNext/Trilium
  .github/workflows/nightly.yml
Labels: size:XS, lgtm

#6624 Translations update from Hosted Weblate
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/sl/translation.json
  apps/client/src/translations/tw/translation.json
  apps/server/src/assets/translations/ja/server.json
  apps/server/src/assets/translations/sl/server.json
  apps/server/src/assets/translations/tw/server.json
Labels: size:XL, lgtm

#6626 Translations update from Hosted Weblate
  apps/client/src/translations/ca/translation.json
  apps/client/src/translations/cn/translation.json
  apps/client/src/translations/de/translation.json
  apps/client/src/translations/el/translation.json
  apps/client/src/translations/es/translation.json
  apps/client/src/translations/fr/translation.json
  apps/client/src/translations/it/translation.json
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/pt_br/translation.json
  apps/client/src/translations/ro/translation.json
  apps/client/src/translations/ru/translation.json
  apps/client/src/translations/sr/translation.json
  apps/client/src/translations/tr/translation.json
  apps/client/src/translations/tw/translation.json
  apps/client/src/translations/vi/translation.json
  apps/server/src/assets/translations/es/server.json
  apps/server/src/assets/translations/ja/server.json
  apps/server/src/assets/translations/ro/server.json
Labels: size:L, merge-conflicts

#6628 docs: ✏️ Improve OIDC docs
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Installation & Setup/Server Installation/1. Installing the server/Packaged version for Linux.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Installation & Setup/Server Installation/1. Installing the server/Using Docker.html
  apps/server/src/assets/doc_notes/en/User Guide/User Guide/Installation & Setup/Server Installation/Multi-Factor Authentication.html
  docs/User Guide/User Guide/Installation & Setup/Server Installation/1. Installing the server/Packaged version for Linux.md
  docs/User Guide/User Guide/Installation & Setup/Server Installation/1. Installing the server/Using Docker.md
  docs/User Guide/User Guide/Installation & Setup/Server Installation/Multi-Factor Authentication.md
Labels: size:L

#6644 feat(logs): provide an option to keep all logs
  apps/server/src/services/log.ts
  docs/User Guide/User Guide/Troubleshooting/Error logs/Backend (server) logs.md
Labels: size:S, lgtm

#6648 Update README.md
  README.md
Labels: size:M

#6661 Translations update from Hosted Weblate
  apps/client/src/translations/fr/translation.json
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/ro/translation.json
  apps/client/src/translations/tw/translation.json
  apps/client/src/translations/vi/translation.json
  apps/server/src/assets/translations/fr/server.json
  apps/server/src/assets/translations/ja/server.json
  apps/server/src/assets/translations/ru/server.json
  apps/server/src/assets/translations/tw/server.json
Labels: size:XL, lgtm

#6657 Fix (Update): No update notification in the global menu
  apps/client/src/widgets/buttons/global_menu.ts
Labels: size:XS

#6663 Translations update from Hosted Weblate
  apps/client/src/translations/fi/translation.json
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/uk/translation.json
  apps/server/src/assets/translations/fi/server.json
  apps/server/src/assets/translations/ru/server.json
  apps/server/src/assets/translations/uk/server.json
Labels: size:L

#6664 Translations update from Hosted Weblate
  apps/client/src/translations/fa/translation.json
  apps/client/src/translations/uk/translation.json
  apps/server/src/assets/translations/fa/server.json
  apps/server/src/assets/translations/uk/server.json
Labels: size:S, lgtm

#6673 Translations update from Hosted Weblate
  apps/client/src/translations/fa/translation.json
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/uk/translation.json
  apps/server/src/assets/translations/fa/server.json
  apps/server/src/assets/translations/fr/server.json
  apps/server/src/assets/translations/uk/server.json
Labels: size:L, lgtm

#6697 Translations update from Hosted Weblate
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/pl/translation.json
  apps/client/src/translations/ru/translation.json
  apps/server/src/assets/translations/hu/server.json
  apps/server/src/assets/translations/ja/server.json
  apps/server/src/assets/translations/pl/server.json
  apps/server/src/assets/translations/ru/server.json
Labels: size:XXL, lgtm

#6732 Translations update from Hosted Weblate
  apps/client/src/translations/ko/translation.json
  apps/client/src/translations/pt_br/translation.json
  apps/client/src/translations/uk/translation.json
  apps/server/src/assets/translations/de/server.json
  apps/server/src/assets/translations/ko/server.json
  apps/server/src/assets/translations/uk/server.json
Labels: size:XXL, lgtm

#6767 Translations update from Hosted Weblate
  apps/client/src/translations/cn/translation.json
  apps/client/src/translations/fr/translation.json
  apps/client/src/translations/ko/translation.json
  apps/client/src/translations/ru/translation.json
  apps/client/src/translations/tw/translation.json
  apps/server/src/assets/translations/de/server.json
  apps/server/src/assets/translations/fr/server.json
  apps/server/src/assets/translations/ko/server.json
  apps/server/src/assets/translations/tw/server.json
Labels: size:L, lgtm

#6770 Fix for casing and formatting in i18n.ts which was causing compile errors
  apps/client/src/widgets/view_widgets/calendar_view.ts
  apps/server/src/services/i18n.ts
  packages/commons/src/lib/i18n.ts
Labels: size:XS

#6726 feat(config): fix previously documented env var formula not working
  apps/server/src/services/config.spec.ts
  apps/server/src/services/config.ts
Labels: size:XL, lgtm

#6752 fix(jump_to): fix issue where attributes/tags don't show in results
  apps/client/src/services/note_autocomplete.ts
  apps/client/src/stylesheets/style.css
  apps/client/src/stylesheets/theme-next/base.css
  apps/client/src/widgets/dialogs/jump_to_note.tsx
Labels: size:L

#6769 feat(quick_search): also allow for the equals operator in note title's quick search
  apps/server/src/services/search/services/lex.spec.ts
  apps/server/src/services/search/services/lex.ts
  apps/server/src/services/search/services/parse.ts
  apps/server/src/services/search/services/search.spec.ts
  apps/server/src/services/search/services/search.ts
  apps/server/test_search_integration.js
  docs/User Guide/User Guide/Basic Concepts and Features/Navigation/Quick search - Exact Match.md
Labels: size:L

#6782 fix: log same error message on api 401 as on login error to allow fail2ban blocking
  apps/server/src/services/auth.ts
Labels: size:XS, lgtm

#6787 Translations update from Hosted Weblate
  apps/client/src/translations/ro/translation.json
Labels: size:M, lgtm

#6802 Translations update from Hosted Weblate
  apps/client/src/translations/de/translation.json
  apps/client/src/translations/pt_br/translation.json
  apps/server/src/assets/translations/de/server.json
Labels: size:L

#6807 Translations update from Hosted Weblate
  apps/client/src/translations/de/translation.json
  apps/client/src/translations/pt_br/translation.json
Labels: size:L, lgtm

#6783 Theme tweaks
  apps/client/src/stylesheets/style.css
  apps/client/src/stylesheets/theme-next-dark.css
  apps/client/src/stylesheets/theme-next-light.css
  apps/client/src/stylesheets/theme-next/forms.css
  apps/client/src/stylesheets/theme-next/shell.css
  apps/client/src/widgets/dialogs/delete_notes.tsx
  apps/client/src/widgets/find.ts
  apps/client/src/widgets/note_icon.css
  apps/client/src/widgets/quick_search.ts
  apps/client/src/widgets/ribbon/SearchDefinitionTab.tsx
  apps/client/src/widgets/ribbon/components/AttributeEditor.tsx
  apps/client/src/widgets/ribbon/style.css
Labels: size:L, lgtm

#6819 Translations update from Hosted Weblate
  apps/client/src/translations/de/translation.json
  apps/client/src/translations/it/translation.json
  apps/client/src/translations/pt_br/translation.json
  apps/client/src/translations/ru/translation.json
  apps/server/src/assets/translations/de/server.json
  apps/server/src/assets/translations/pt_br/server.json
Labels: size:XXL, lgtm

#6830 Port small widgets to React
  apps/client/src/components/app_context.ts
  apps/client/src/components/entrypoints.ts
  apps/client/src/layouts/desktop_layout.tsx
  apps/client/src/layouts/mobile_layout.tsx
  apps/client/src/services/keyboard_actions.ts
  apps/client/src/services/server.ts
  apps/client/src/services/utils.ts
  apps/client/src/stylesheets/style.css
  apps/client/src/stylesheets/theme-next/base.css
  apps/client/src/stylesheets/theme-next/pages.css
  apps/client/src/translations/en/translation.json
  apps/client/src/widgets/api_log.css
  apps/client/src/widgets/api_log.ts
  apps/client/src/widgets/api_log.tsx
  apps/client/src/widgets/basic_widget.ts
  apps/client/src/widgets/buttons/global_menu.css
  apps/client/src/widgets/buttons/global_menu.ts
  apps/client/src/widgets/buttons/global_menu.tsx
  apps/client/src/widgets/buttons/history_navigation.ts
  apps/client/src/widgets/buttons/left_pane_toggle.ts
  apps/client/src/widgets/buttons/left_pane_toggle.tsx
  apps/client/src/widgets/buttons/update_available.ts
  apps/client/src/widgets/close_zen_button.css
  apps/client/src/widgets/close_zen_button.ts
  apps/client/src/widgets/close_zen_button.tsx
  apps/client/src/widgets/mobile_widgets/mobile_detail_menu.ts
  apps/client/src/widgets/mobile_widgets/mobile_detail_menu.tsx
  apps/client/src/widgets/mobile_widgets/toggle_sidebar_button.ts
  apps/client/src/widgets/mobile_widgets/toggle_sidebar_button.tsx
  apps/client/src/widgets/react/ActionButton.tsx
  apps/client/src/widgets/react/Alert.tsx
  apps/client/src/widgets/react/Dropdown.tsx
  apps/client/src/widgets/react/FormList.tsx
  apps/client/src/widgets/react/KeyboardShortcut.tsx
  apps/client/src/widgets/react/hooks.tsx
  apps/client/src/widgets/react/react_utils.tsx
  apps/client/src/widgets/ribbon/Ribbon.tsx
  apps/client/src/widgets/scroll_padding.ts
  apps/client/src/widgets/scroll_padding.tsx
  apps/client/src/widgets/search_result.css
  apps/client/src/widgets/search_result.ts
  apps/client/src/widgets/search_result.tsx
  apps/client/src/widgets/sql_result.css
  apps/client/src/widgets/sql_result.ts
  apps/client/src/widgets/sql_result.tsx
  apps/client/src/widgets/sql_table_schemas.css
  apps/client/src/widgets/sql_table_schemas.ts
  apps/client/src/widgets/sql_table_schemas.tsx
  apps/client/src/widgets/title_bar_buttons.css
  apps/client/src/widgets/title_bar_buttons.ts
  apps/client/src/widgets/title_bar_buttons.tsx
  apps/client/src/widgets/type_widgets/ckeditor/mobile_editor_toolbar.css
  apps/client/src/widgets/type_widgets/ckeditor/mobile_editor_toolbar.ts
  apps/client/src/widgets/type_widgets/ckeditor/mobile_editor_toolbar.tsx
  apps/server/src/routes/api/notes.ts
  apps/server/src/routes/api/sql.ts
  packages/commons/src/lib/server_api.ts
Labels: size:XXL

#6821 fix(tree): defend against stray null values that may occur when multi…
  apps/server/src/services/tree.ts
Labels: size:XS, lgtm

#6838 Translations update from Hosted Weblate
  apps/client/src/translations/cn/translation.json
  apps/client/src/translations/tw/translation.json
  apps/server/src/assets/translations/tw/server.json
Labels: size:M, lgtm
