Repository TriliumNext/Trilium, pull requests merged in 2025-09, with the labels that each got.

#6912 Add an option to disable smooth scrolling for the Electron app
  apps/client/src/translations/en/translation.json
  apps/client/src/translations/ro/translation.json
  apps/client/src/widgets/type_widgets/options/appearance.tsx
  apps/desktop/src/main.ts
  apps/server/src/routes/api/options.ts
  apps/server/src/services/options_init.ts
  packages/commons/src/lib/options_interface.ts
Labels: size:S, lgtm

#6887 feat: show source diff between note and revision
  apps/client/src/services/utils.ts
  apps/client/src/stylesheets/style.css
  apps/client/src/translations/en/translation.json
  apps/client/src/widgets/dialogs/revisions.tsx
  apps/client/src/widgets/type_widgets/read_only_code.ts
Labels: size:L, lgtm

#6866 feat: Make splits resizable
  apps/client/src/services/resizer.ts
  apps/client/src/stylesheets/style.css
  apps/client/src/stylesheets/theme-next/shell.css
  apps/client/src/widgets/containers/split_note_container.ts
Labels: size:L, lgtm

#6847 Apply note wrapper on mobile
  apps/client/src/layouts/mobile_layout.tsx
  apps/client/src/widgets/note_wrapper.ts
Labels: size:M, lgtm

#6916 Translations update from Hosted Weblate
  apps/server/src/assets/translations/pl/server.json
Labels: size:XS, lgtm

#6851 fix(shortcuts): try to fix ime composition checks
  apps/client/src/services/shortcuts.spec.ts
  apps/client/src/services/shortcuts.ts
  apps/client/src/widgets/find.ts
  apps/client/src/widgets/note_title.tsx
  apps/client/src/widgets/quick_search.ts
  apps/client/src/widgets/ribbon/components/AttributeEditor.tsx
Labels: size:M, lgtm

#6935 Translations update from Hosted Weblate
  apps/client/src/translations/it/translation.json
  apps/client/src/translations/ru/translation.json
Labels: size:S, lgtm

#6990 feat(readme): update readme with new docs site
  README.md
Labels: size:M, lgtm

#7003 Translations update from Hosted Weblate
  apps/client/src/translations/tr/translation.json
Labels: size:L, lgtm

#7002 Fix(build): Fix the issue that on ARM64 Linux failed to launch due to missing better_sqlite3.node
  .github/actions/build-electron/action.yml
  .github/workflows/release.yml
  scripts/electron-rebuild.mts
Labels: size:S, lgtm

#7022 Translations update from Hosted Weblate
  apps/client/src/translations/de/translation.json
  apps/server/src/assets/translations/de/server.json
Labels: size:M, lgtm

#7027 Translations update from Hosted Weblate
  apps/client/src/translations/pt/translation.json
  apps/server/src/assets/translations/pt/server.json
Labels: size:L, lgtm

#7036 UI / theme improvements
  apps/client/src/menus/context_menu.ts
  apps/client/src/menus/electron_context_menu.ts
  apps/client/src/menus/launcher_context_menu.ts
  apps/client/src/menus/tree_context_menu.ts
  apps/client/src/services/note_types.ts
  apps/client/src/stylesheets/style.css
  apps/client/src/stylesheets/theme-next/base.css
  apps/client/src/stylesheets/theme-next/forms.css
  apps/client/src/stylesheets/theme-next/shell.css
  apps/client/src/widgets/collections/board/context_menu.ts
  apps/client/src/widgets/collections/geomap/context_menu.ts
  apps/client/src/widgets/collections/table/context_menu.ts
  apps/client/src/widgets/dialogs/bulk_actions.css
  apps/client/src/widgets/dialogs/note_type_chooser.tsx
  apps/client/src/widgets/mobile_widgets/mobile_detail_menu.tsx
  apps/client/src/widgets/ribbon/components/AttributeEditor.tsx
  apps/client/src/widgets/tab_row.ts
Labels: size:L

#7043 Translations update from Hosted Weblate
  apps/client/src/translations/pt_br/translation.json
  apps/client/src/translations/ru/translation.json
  apps/server/src/assets/translations/pt_br/server.json
  apps/server/src/assets/translations/ru/server.json
Labels: size:M, lgtm

#7046 UI improvements
  apps/client/src/stylesheets/style.css
  apps/client/src/stylesheets/theme-next-dark.css
  apps/client/src/stylesheets/theme-next/base.css
  apps/client/src/stylesheets/theme-next/forms.css
  apps/client/src/stylesheets/theme-next/pages.css
  apps/client/src/stylesheets/theme-next/shell.css
  apps/client/src/widgets/FloatingButtons.css
  apps/client/src/widgets/buttons/global_menu.css
Labels: size:L

#7053 Update typo in ru translation
  apps/client/src/translations/ru/translation.json
Labels: size:XS, lgtm

#7094 fix(client): Use number sorting for number columns in Table view
  apps/client/src/widgets/collections/table/columns.tsx
Labels: size:XS, lgtm

#7100 Translations update from Hosted Weblate
  apps/client/src/translations/cn/translation.json
  apps/client/src/translations/cs/translation.json
  apps/client/src/translations/es/translation.json
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/ru/translation.json
  apps/client/src/translations/tw/translation.json
  apps/server/src/assets/translations/cs/server.json
  apps/server/src/assets/translations/ja/server.json
Labels: size:L, lgtm

#7118 Translations update from Hosted Weblate
  apps/client/src/translations/ja/translation.json
  apps/client/src/translations/ru/translation.json
  apps/server/src/assets/translations/hr/server.json
  apps/server/src/assets/translations/ja/server.json
Labels: size:L, lgtm

#7125 Automatically resize webview
  apps/client/src/widgets/type_widgets/web_view.ts
Labels: size:S, lgtm
